package com.lakesidegames.electioneer.engine

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.math.abs

// Phase 1, issue #16 (actions half): scripted action scenarios replayed
// against the real TS engine. All expected values were generated by running
// src/engine/actions.ts on identical fixtures (scripts in /tmp).
//
// Platform note: V8 and JVM transcendentals disagree by 1 ulp on some inputs
// (measured: Math.exp(-1/6) = ...223b0 on V8 vs ...223b1 on the JVM), so any
// value downstream of exp/ln/sqrt/cos asserts within 1e-12 instead of exactly.
// The RNG stream itself uses no transcendentals and stays bit-identical, and
// everything else (counts, strings, cash, EVs) asserts exactly.
class ActionsTest {

    private fun traits() = CandidateTraits(
        charisma = 60.0, energy = 50.0, debatePrep = 60.0, intelligence = 60.0,
        policyKnowledge = 60.0, debatingSkill = 60.0, fundraisingProwess = 70.0,
    )

    private fun cand(id: CandidateId) = Candidate(
        id = id,
        name = id.serial,
        shortName = id.serial,
        party = if (id == CandidateId.DEM) Party.DEMOCRATIC else Party.REPUBLICAN,
        runningMate = "VP",
        color = "#000",
        traits = traits(),
        issuePositions = mutableMapOf(
            "economy" to if (id == CandidateId.DEM) -0.2 else 0.4,
            "healthcare" to -0.1,
        ),
        baseFavorability = emptyMap(),
    )

    private fun bloc(id: BlocId, baseline: Double, size: Double = 1000.0) = StateBloc(
        blocId = id, size = size, turnoutPropensity = 0.6, baselineMargin = baseline,
        support = emptyMap(), campaignMargin = 0.0, enthusiasm = 1.0,
    )

    private fun state(id: String, ev: Int, momentum: Double = 0.0) = StateContest(
        id = id, name = id, abbr = id, electoralVotes = ev, region = Region.SWING,
        prior2020DemShare = 0.5, mediaMarketCost = 1.0, battleground = true,
        blocs = listOf(
            bloc(BlocId.NONCOLLEGE_WHITE, 0.2),
            bloc(BlocId.SUBURBAN_WOMEN, -0.1, 800.0),
        ),
        groundGame = mutableMapOf("dem" to 0.0, "rep" to 0.0),
        momentum = momentum,
    )

    private fun res(cash: Double, staffCapacity: Int = 3) = Resources(
        cash = cash, actions = 7, maxActions = 7, staffCapacity = staffCapacity,
        nationalMomentum = 0.0, mediaNarrative = 0.0,
    )

    private fun game(cash: Double = 10_000_000.0) = GameState(
        seed = 5, rngState = 5, turn = 0, totalTurns = 10, granularity = "week",
        phase = GamePhase.INTEL, playerCandidate = CandidateId.DEM, playerEdge = 1.0,
        candidates = mapOf("dem" to cand(CandidateId.DEM), "rep" to cand(CandidateId.REP)),
        issues = emptyMap(),
        salience = mutableMapOf("economy" to 0.5, "healthcare" to 0.5),
        states = listOf(state("PA", 19, 5.0)),
        resources = mapOf("dem" to res(cash), "rep" to res(10_000_000.0)),
        pendingEvents = mutableListOf(), firedEventIds = mutableListOf(),
        queuedActions = emptyList(),
        causes = mutableListOf(), lastRecap = emptyList(),
        staff = emptyMap(),
    )

    private fun act(
        type: ActionType, c: CandidateId, stateId: String? = null, spend: Double? = null,
        adMode: AdMode? = null, issueId: IssueId? = null, newPosition: Double? = null,
    ) = CampaignAction(
        type = type, candidate = c, stateId = stateId, spend = spend,
        adMode = adMode, issueId = issueId, newPosition = newPosition,
    )

    @Test
    fun scriptedWeekMatchesTs() {
        val g = game()
        val rng = Rng.createRng("script")
        val dem = CandidateId.DEM
        val rep = CandidateId.REP
        applyAction(g, act(ActionType.ADVERTISE, dem, "PA", spend = 2_000_000.0), rng)
        applyAction(g, act(ActionType.ADVERTISE, dem, "PA", spend = 1_000_000.0, adMode = AdMode.CONTRAST), rng)
        applyAction(
            g,
            act(ActionType.ADVERTISE, dem, "PA", spend = 500_000.0, adMode = AdMode.ISSUE, issueId = IssueId.ECONOMY),
            rng,
        )
        applyAction(g, act(ActionType.RALLY, dem, "PA"), rng)
        applyAction(g, act(ActionType.SURROGATE, rep, "PA"), rng)
        applyAction(g, act(ActionType.FUNDRAISE, dem, "PA"), rng)
        applyAction(g, act(ActionType.FUNDRAISE, rep), rng)
        applyAction(g, act(ActionType.GROUND_GAME, dem, "PA"), rng)
        applyAction(g, act(ActionType.GOTV, rep, "PA"), rng)
        applyAction(g, act(ActionType.GOTV, dem, "PA"), rng)
        applyAction(g, act(ActionType.POLICY_PREP, rep), rng)
        // dem is now out of slots: these three are no-ops.
        applyAction(g, act(ActionType.OPPO_RESEARCH, dem, "PA"), rng)
        applyAction(g, act(ActionType.DEBATE_PREP, dem), rng)
        applyAction(g, act(ActionType.ISSUE_PIVOT, dem, issueId = IssueId.ECONOMY, newPosition = 0.5), rng)
        applyAction(g, act(ActionType.RALLY, dem, "ZZ"), rng)

        val st = g.states[0]
        assertCloseList(
            listOf(0.1321627570803199, 0.13973979212623716),
            st.blocs.map { it.campaignMargin },
            "margins",
        )
        assertEquals(listOf(0.998, 0.998), st.blocs.map { it.enthusiasm })
        assertEquals(12.0, st.momentum)
        assertEquals(mapOf("dem" to 0.2, "rep" to 0.0), st.groundGame.toMap())

        val demRes = g.resources.getValue("dem")
        assertEquals(26056135.973210037, demRes.cash)
        assertEquals(0, demRes.actions)
        assertEquals(2, demRes.staffCapacity)
        assertEquals(1.5, demRes.nationalMomentum)
        assertEquals(-4.0, demRes.mediaNarrative)
        val repRes = g.resources.getValue("rep")
        assertEquals(26285840.280642733, repRes.cash)
        assertEquals(3, repRes.actions)

        assertEquals(mapOf("economy" to 0.5075, "healthcare" to 0.5), g.salience.toMap())
        assertEquals(mapOf("dem" to 3500000.0), g.adSpend?.toMap())
        assertEquals(
            mapOf("dem" to 22056135.973210037, "rep" to 17535840.280642733),
            g.fundsRaised?.toMap(),
        )
        assertEquals(mapOf("dem" to "PA"), g.locations?.toMap())

        val expected = listOf(
            Triple("Positive ads in PA", "noncollege_white", 0.07629572986081022),
            Triple("Positive ads in PA", "suburban_women", 0.07858989819609322),
            Triple("Contrast ads in PA", "noncollege_white", 0.021509912851408436),
            Triple("Contrast ads in PA", "suburban_women", 0.019871389641284366),
            Triple("Issue ads raised salience of economy", null, 0.0),
            Triple("Rally in PA", "noncollege_white", 0.030918142524396876),
            Triple("Rally in PA", "suburban_women", 0.037377313208023115),
            Triple("Surrogate visit to PA", "noncollege_white", -0.00974383603147308),
            Triple("Surrogate visit to PA", "suburban_women", -0.011143090980418218),
            Triple("PA fundraiser (+\$22.1M)", null, 0.0),
            Triple("Fundraising haul (+\$17.5M)", null, 0.0),
            Triple("Built field offices in PA", null, 0.0),
            Triple("GOTV in PA fell flat (no field operation)", null, 0.0),
            Triple("GOTV mobilization in PA", "noncollege_white", 0.01318280787517744),
            Triple("GOTV mobilization in PA", "suburban_women", 0.015044282061254698),
            Triple("Policy prep (+8 policy command)", null, 0.0),
        )
        assertEquals(expected.size, g.causes.size)
        expected.forEachIndexed { i, (cause, bloc, delta) ->
            assertEquals(cause, g.causes[i].cause, "cause $i")
            assertEquals(bloc, g.causes[i].blocId?.serial, "bloc $i")
            assertClose(delta, g.causes[i].marginDelta, "delta $i")
        }
        assertEquals("PA", g.causes[9].stateId)
        assertNull(g.causes[10].stateId)

        // Out-of-slots probe: untouched.
        val cashBefore = demRes.cash
        val causesBefore = g.causes.size
        applyAction(g, act(ActionType.RALLY, dem, "PA"), rng)
        assertEquals(cashBefore, demRes.cash)
        assertEquals(causesBefore, g.causes.size)
    }

    @Test
    fun gatedNoOpsOppoDebatePivotMatchTs() {
        val g = game(100.0)
        val rng = Rng.createRng("script2")
        val dem = CandidateId.DEM
        applyAction(g, act(ActionType.SURROGATE, dem, "PA"), rng)
        applyAction(g, act(ActionType.GROUND_GAME, dem, "PA"), rng)
        applyAction(g, act(ActionType.OPPO_RESEARCH, dem, "PA"), rng)
        // Slots consumed, nothing else happened.
        assertEquals(100.0, g.resources.getValue("dem").cash)
        assertTrue(g.causes.isEmpty())
        assertEquals(4, g.resources.getValue("dem").actions)

        g.resources.getValue("dem").cash = 10_000_000.0
        g.resources.getValue("dem").actions = 7
        applyAction(g, act(ActionType.OPPO_RESEARCH, dem, "PA"), rng)
        applyAction(g, act(ActionType.DEBATE_PREP, dem), rng)
        applyAction(
            g,
            act(ActionType.ISSUE_PIVOT, dem, issueId = IssueId.ECONOMY, newPosition = 0.5),
            rng,
        )
        // Sub-threshold move: no-op.
        applyAction(
            g,
            act(ActionType.ISSUE_PIVOT, dem, issueId = IssueId.ECONOMY, newPosition = 0.505),
            rng,
        )
        // Unknown state: slot consumed, no effect.
        applyAction(g, act(ActionType.RALLY, dem, "ZZ"), rng)

        val st = g.states[0]
        assertCloseList(
            listOf(0.04500000000000002, 0.001472881355932194),
            st.blocs.map { it.campaignMargin },
            "margins2",
        )
        val demRes = g.resources.getValue("dem")
        assertEquals(8000000.0, demRes.cash)
        assertEquals(2, demRes.actions)
        assertEquals(6.0, demRes.mediaNarrative)
        assertEquals(68.0, g.candidates.getValue("dem").traits.debatePrep)
        assertEquals(0.5, g.candidates.getValue("dem").issuePositions.getValue("economy"))

        val expected = listOf(
            Triple("Scandal lands on rep", "suburban_women", 0.04237288135593221),
            Triple("Debate prep (+8 debate readiness)", null, 0.0),
            Triple("Pivot on economy", "noncollege_white", 0.04500000000000002),
            Triple("Pivot on economy", "suburban_women", -0.032500000000000015),
            Triple("\"Flip-flopper\" cost on economy", "suburban_women", -0.0084),
        )
        assertEquals(expected.size, g.causes.size)
        expected.forEachIndexed { i, (cause, bloc, delta) ->
            assertEquals(cause, g.causes[i].cause, "cause $i")
            assertEquals(bloc, g.causes[i].blocId?.serial, "bloc $i")
            assertClose(delta, g.causes[i].marginDelta, "delta2 $i")
        }
    }

    private fun assertClose(expected: Double, actual: Double, label: String) {
        assertTrue(abs(expected - actual) <= 1e-12, "$label expected $expected but was $actual")
    }

    private fun assertCloseList(expected: List<Double>, actual: List<Double>, label: String) {
        assertEquals(expected.size, actual.size, "$label size")
        expected.forEachIndexed { i, e -> assertClose(e, actual[i], "$label[$i]") }
    }
}
