package com.lakesidegames.electioneer.engine

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

// Phase 1, issue #14: system/polls/voteModel ports stay byte-identical to TS
// on the US two-party path. All expected values were generated by running the
// real TS against the same synthetic fixtures (scripts in /tmp).
class CoreSimTest {

    private fun bloc(
        baseline: Double,
        campaign: Double,
        size: Double = 1000.0,
        turnout: Double = 0.6,
        enthusiasm: Double = 1.0,
    ) = StateBloc(
        blocId = BlocId.NONCOLLEGE_WHITE,
        size = size,
        turnoutPropensity = turnout,
        baselineMargin = baseline,
        support = mapOf("dem" to 0.5, "rep" to 0.5),
        campaignMargin = campaign,
        enthusiasm = enthusiasm,
    )

    private fun contest(
        id: String,
        ev: Int,
        blocs: List<StateBloc>,
        momentum: Double = 0.0,
        aggregateOf: List<String>? = null,
    ) = StateContest(
        id = id,
        name = id,
        abbr = id,
        electoralVotes = ev,
        region = Region.SWING,
        prior2020DemShare = 0.5,
        mediaMarketCost = 1.0,
        battleground = false,
        blocs = blocs,
        groundGame = emptyMap(),
        momentum = momentum,
        aggregateOf = aggregateOf,
    )

    private val pa = contest(
        "PA", 19,
        listOf(
            bloc(0.2, 0.05, 1000.0, 0.6, 1.0),
            bloc(-0.3, 0.1, 800.0, 0.5, 1.1),
        ),
        momentum = 10.0,
    )
    private val oh = contest(
        "OH", 17, listOf(bloc(0.0, -0.05, 500.0, 0.55, 0.9)), momentum = -20.0,
    )
    private val hi = contest("HI", 4, listOf(bloc(10.0, 0.0, 100.0, 0.5, 1.0)))
    private val lo = contest("LO", 3, listOf(bloc(-10.0, 0.0, 100.0, 0.5, 1.0)))
    private val me1 = contest("ME1", 1, listOf(bloc(0.5, 0.0, 300.0)))
    private val me2 = contest("ME2", 1, listOf(bloc(-0.5, 0.0, 300.0)))
    private val meAl = contest("ME-AL", 2, emptyList(), aggregateOf = listOf("ME1", "ME2"))

    private fun game() = GameState(
        seed = 12345,
        rngState = 99,
        turn = 3,
        totalTurns = 10,
        granularity = "week",
        phase = GamePhase.RESULT,
        playerCandidate = CandidateId.DEM,
        candidates = emptyMap(),
        issues = emptyMap(),
        salience = emptyMap(),
        states = listOf(pa, oh, hi, lo, me1, me2, meAl),
        resources = emptyMap(),
        pendingEvents = emptyList(),
        firedEventIds = emptyList(),
        queuedActions = emptyList(),
        causes = listOf(0.5, -0.5, 0.3, 0.3, -0.2, 0.1, 0.0, 1.5, -1.2, 0.8).mapIndexed { i, d ->
            CauseEntry(turn = 1, cause = "c$i", marginDelta = d)
        },
        lastRecap = emptyList(),
    )

    @Test
    fun blocDemShareMatchesTs() {
        assertEquals(0.5621765008857981, blocDemShare(0.2, 0.05))
    }

    @Test
    fun liveBlocDemShareIncludesMomentumCoupling() {
        assertEquals(0.5663562616210012, liveBlocDemShare(pa, pa.blocs[0]))
    }

    @Test
    fun tallyContestMatchesTs() {
        val t = tallyContest(pa)
        assertEquals(539.7397472716609, t.demVotes)
        assertEquals(500.2602527283391, t.repVotes)
        assertEquals(1040.0, t.totalVotes)
        assertEquals(0.5189805262227509, t.demShare)
        assertEquals(CandidateId.DEM, t.winner)
    }

    @Test
    fun tallyContestRepWinMatchesTs() {
        val t = tallyContest(oh)
        assertEquals(118.55555397513324, t.demVotes)
        assertEquals(0.47901233929346765, t.demShare)
        assertEquals(CandidateId.REP, t.winner)
    }

    @Test
    fun tallyEmptyContestDefaultsToDemHalf() {
        val t = tallyContest(contest("XX", 3, emptyList()))
        assertEquals(0.0, t.demVotes)
        assertEquals(0.5, t.demShare)
        assertEquals(CandidateId.DEM, t.winner)
    }

    @Test
    fun computeResultMatchesTs() {
        val r = computeResult(game())
        assertEquals(mapOf("dem" to 26, "rep" to 21), r.electoralVotes)
        assertEquals("tie", r.winner)
        assertEquals(888.2953012467942, r.popularVote.getValue("dem"))
        assertEquals(859.2046987532058, r.popularVote.getValue("rep"))
        assertEquals(0.5083234914144745, r.popularShare.getValue("dem"))
        assertEquals(0.4916765085855255, r.popularShare.getValue("rep"))
        assertEquals(7, r.stateResults.size)
        val paRes = r.stateResults.first { it.stateId == "PA" }
        assertEquals(0.5189805262227509, paRes.demShare)
        assertEquals(3.7961052445501853, paRes.margin)
        val meAl = r.stateResults.first { it.stateId == "ME-AL" }
        assertEquals(0.5, meAl.demShare)
        assertEquals(CandidateId.DEM, meAl.winner)
        assertEquals(0.0, meAl.margin)
    }

    @Test
    fun postMortemTakesTopEightByMagnitudeStably() {
        val r = computeResult(game())
        assertEquals(
            listOf(1.5, -1.2, 0.8, 0.5, -0.5, 0.3, 0.3, -0.2),
            r.postMortem.map { it.marginDelta },
        )
    }

    @Test
    fun projectElectionMatchesTs() {
        val p = projectElection(game())
        assertEquals(mapOf("dem" to 24, "rep" to 21), p.ev)
        assertEquals(2, p.tossupEv)
        assertEquals(
            listOf("dem", "rep", "dem", "rep", "dem", "rep", "tossup"),
            p.contests.map { it.lean },
        )
    }

    @Test
    fun projectElectionZeroBandKeepsExactTieTossup() {
        val p = projectElection(game(), 0)
        assertEquals(2, p.tossupEv)
        assertEquals("tossup", p.contests.first { it.stateId == "ME-AL" }.lean)
        assertEquals("dem", p.contests.first { it.stateId == "PA" }.lean)
    }

    @Test
    fun pollStateMatchesTs() {
        val polls = pollState(game(), "PA")
        assertEquals(5, polls.size)
        assertEquals("Quinnipiac", polls[0].pollster)
        assertEquals(0.5094944867210545, polls[0].demShare)
        assertEquals(1100, polls[0].sampleSize)
        assertEquals(3.0, polls[0].marginOfError)
        assertEquals(0.5319053735422371, polls[1].demShare)
        assertEquals(3.1, polls[1].marginOfError)
        assertEquals(3.3, polls[2].marginOfError)
        assertEquals(3.0, polls[3].marginOfError)
        assertEquals(0.49040353290051925, polls[4].demShare)
        assertEquals(3.5, polls[4].marginOfError)
    }

    @Test
    fun pollStateClampsToUnitInterval() {
        assertEquals(0.99, pollState(game(), "HI")[0].demShare)
        // Low side: sampling noise lands inside bounds here, still exact.
        assertEquals(0.03863148234398719, pollState(game(), "LO")[0].demShare)
    }

    @Test
    fun pollStateEmptyForUnknownContest() {
        assertTrue(pollState(game(), "ZZ").isEmpty())
        assertNull(pollAverage(game(), "ZZ"))
    }

    @Test
    fun pollAverageAndNationalMatchTs() {
        assertEquals(0.5135174837214571, pollAverage(game(), "PA"))
        assertEquals(0.5038756967050797, nationalPoll(game()))
    }

    @Test
    fun partyByIdFindsAndMisses() {
        val sys = PoliticalSystem(
            id = "US",
            label = "US",
            parties = listOf(PartyDef(id = "dem", name = "Dem", shortName = "D", color = "#00f")),
            allocation = AllocationStrategy(
                id = AllocationStrategyId.WINNER_TAKE_ALL_EV, label = "x", unit = "ev",
            ),
            majority = MajorityRule(total = 538, threshold = 270),
        )
        assertEquals("Dem", partyById(sys, "dem")?.name)
        assertEquals(null, partyById(sys, "rep"))
    }
}
