package com.lakesidegames.electioneer.engine

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

// Scoring, runoff, and achievements against the real TS implementations.
// Vectors generated by running the TS sources (scripts in /tmp).
class MiscTest {

    @Test
    fun scoresMatchTs() {
        assertEquals(
            653,
            computeScoreFromFacts(ScoreFacts(unitMargin = 36.0, chamberSize = 538, popularMargin = 4.5, difficulty = "normal")),
        )
        assertEquals(
            180,
            computeScoreFromFacts(ScoreFacts(unitMargin = -100.0, chamberSize = 538, popularMargin = -8.0, difficulty = "hard")),
        )
        assertEquals(
            560,
            computeScoreFromFacts(ScoreFacts(unitMargin = 100.0, chamberSize = 650, popularMargin = 12.0, difficulty = "easy")),
        )
        assertEquals(
            500,
            computeScoreFromFacts(ScoreFacts(unitMargin = 0.0, chamberSize = 0, popularMargin = 0.0, difficulty = "normal")),
        )
    }

    @Test
    fun usScoreFactsMatchTs() {
        val f = usScoreFacts(
            mapOf("dem" to 306, "rep" to 232),
            mapOf("dem" to 0.523, "rep" to 0.477),
            CandidateId.DEM, "normal",
        )
        assertEquals(36.0, f.unitMargin)
        assertEquals(538, f.chamberSize)
        assertEquals(4.600000000000004, f.popularMargin)
    }

    @Test
    fun multipartyScoreFactsMatchTs() {
        val f = multipartyScoreFacts(
            mapOf("con" to 330, "lab" to 250),
            mapOf("con" to 0.42, "lab" to 0.38, "ld" to 0.1),
            "con", 326, 650, "normal",
        )
        assertEquals(4.0, f.unitMargin)
        assertEquals(3.9999999999999982, f.popularMargin)
    }

    @Test
    fun topTwoMatchesTs() {
        assertEquals("b" to "a", topTwo(mapOf("a" to 0.3, "b" to 0.45, "c" to 0.25)))
        // Ties keep content order.
        assertEquals("a" to "b", topTwo(mapOf("x" to 0.0, "a" to 0.4, "b" to 0.4, "c" to 0.2)))
        assertFailsWith<IllegalArgumentException> { topTwo(mapOf("solo" to 1.0)) }
    }

    @Test
    fun runoffMatchesTs() {
        val r = advanceToRunoff(
            mapOf("a" to 0.35, "b" to 0.3, "c" to 0.2, "d" to 0.15),
            mapOf("c" to mapOf("a" to 0.6, "b" to 0.2, "_abstain" to 0.1), "d" to mapOf("b" to 0.7)),
        )
        assertEquals("a" to "b", r.finalists)
        assertEquals(listOf("c", "d"), r.eliminated)
        assertEquals(0.5136612021857924, r.secondRound.getValue("a"))
        assertEquals(0.48633879781420764, r.secondRound.getValue("b"))
        assertEquals(0.47, r.transferred.getValue("a"))
        assertEquals(0.44499999999999995, r.transferred.getValue("b"))
        assertEquals(0.085, r.abstentionRate)
        assertFailsWith<IllegalArgumentException> { advanceToRunoff(mapOf("a" to 0.0, "b" to 0.0), emptyMap()) }
    }

    @Test
    fun regionalRunoffMatchesTs() {
        val (pair, regions) = regionalRunoff(
            mapOf(
                "r1" to mapOf("a" to 0.4, "b" to 0.3, "c" to 0.3),
                "r2" to mapOf("a" to 0.2, "b" to 0.5, "c" to 0.3),
            ),
            mapOf("c" to mapOf("a" to 0.5, "b" to 0.5)),
        )
        assertEquals("b" to "a", pair)
        assertEquals(0.44999999999999996, regions.getValue("r1").getValue("b"))
        assertEquals(0.55, regions.getValue("r1").getValue("a"))
        assertEquals(0.65, regions.getValue("r2").getValue("b"))
        assertEquals(0.35, regions.getValue("r2").getValue("a"))
    }

    private fun bloc() = StateBloc(
        blocId = BlocId.NONCOLLEGE_WHITE, size = 1000.0, turnoutPropensity = 0.6,
        baselineMargin = 0.0, support = emptyMap(), campaignMargin = 0.0, enthusiasm = 1.0,
    )

    private fun st(id: String, prior: Double, battleground: Boolean) = StateContest(
        id = id, name = id, abbr = id, electoralVotes = 10, region = Region.SWING,
        prior2020DemShare = prior, mediaMarketCost = 1.0, battleground = battleground,
        blocs = listOf(bloc()), groundGame = mutableMapOf(), momentum = 0.0,
    )

    private fun sr(id: String, ev: Int, share: Double, winner: CandidateId, margin: Double) =
        StateResult(stateId = id, electoralVotes = ev, demShare = share, winner = winner, margin = margin)

    private fun achGame(): GameState {
        val result = GameResult(
            electoralVotes = mapOf("dem" to 400, "rep" to 138),
            winner = "dem",
            popularVote = mapOf("dem" to 80_000_000.0, "rep" to 70_000_000.0),
            popularShare = mapOf("dem" to 0.533, "rep" to 0.467),
            stateResults = listOf(
                sr("PA", 19, 0.52, CandidateId.DEM, 4.0),
                sr("MI", 16, 0.51, CandidateId.DEM, 2.0),
                sr("WI", 10, 0.505, CandidateId.DEM, 1.0),
                sr("AZ", 11, 0.51, CandidateId.DEM, 2.0),
                sr("GA", 16, 0.503, CandidateId.DEM, 0.6),
                sr("NV", 6, 0.52, CandidateId.DEM, 4.0),
                sr("DC", 3, 0.96, CandidateId.DEM, 92.0),
                sr("CA", 55, 0.64, CandidateId.DEM, 28.0),
                sr("NY", 29, 0.6, CandidateId.DEM, 20.0),
                sr("FL", 29, 0.55, CandidateId.DEM, 10.0),
                sr("TX", 40, 0.53, CandidateId.DEM, 6.0),
            ),
            postMortem = emptyList(),
        )
        return GameState(
            seed = 1, rngState = 1, turn = 9, totalTurns = 9, granularity = "week",
            phase = GamePhase.RESULT, playerCandidate = CandidateId.DEM,
            candidates = mapOf(
                "dem" to Candidate(
                    id = CandidateId.DEM, name = "Biden", shortName = "Biden",
                    party = Party.DEMOCRATIC, runningMate = "VP", color = "#000",
                    traits = CandidateTraits(60.0, 50.0, 60.0, 60.0, 60.0, 60.0, 70.0),
                    issuePositions = mutableMapOf(), baseFavorability = mutableMapOf(),
                ),
                "rep" to Candidate(
                    id = CandidateId.REP, name = "Trump", shortName = "Trump",
                    party = Party.REPUBLICAN, runningMate = "VP", color = "#000",
                    traits = CandidateTraits(60.0, 50.0, 60.0, 60.0, 60.0, 60.0, 70.0),
                    issuePositions = mutableMapOf(), baseFavorability = mutableMapOf(),
                ),
            ),
            issues = emptyMap(), salience = mutableMapOf(),
            states = listOf(
                st("PA", 0.49, true), st("MI", 0.51, true),
                st("WI", 0.5, true), st("TX", 0.47, false),
            ),
            resources = mapOf(
                "dem" to Resources(cash = 60_000_000.0, actions = 7, maxActions = 7, staffCapacity = 3, nationalMomentum = 0.0, mediaNarrative = 0.0),
                "rep" to Resources(cash = 1.0, actions = 7, maxActions = 7, staffCapacity = 3, nationalMomentum = 0.0, mediaNarrative = 0.0),
            ),
            pendingEvents = mutableListOf(), firedEventIds = mutableListOf(),
            queuedActions = emptyList(),
            causes = mutableListOf(
                CauseEntry(turn = 1, cause = "Scandal lands on Trump", marginDelta = 0.05),
            ),
            lastRecap = emptyList(),
            runningMates = mapOf("dem" to "harris"),
            adSpend = mutableMapOf("dem" to 0.0),
            fundsRaised = mutableMapOf("dem" to 200_000_000.0),
            debateHistory = mutableListOf(
                DebateResult("d1", "t", mapOf("dem" to 80.0, "rep" to 60.0), emptyMap(), emptyMap(), "dem", 20.0, false, 10.0),
                DebateResult("d2", "t", mapOf("dem" to 75.0, "rep" to 60.0), emptyMap(), emptyMap(), "dem", 15.0, false, 9.0),
            ),
            timeline = mutableListOf(
                TurnPoint(turn = 4, demPoll = 0.5, demEV = 200, repEV = 338, tossupEV = 0, demMomentum = 0.0, repMomentum = 0.0, demCash = 0.0, repCash = 0.0),
            ),
            result = result,
        )
    }

    @Test
    fun achievementsMatchTs() {
        val g = achGame()
        val ids = checkAchievements(
            AchievementContext(result = g.result!!, game = g, player = CandidateId.DEM, difficulty = "hard"),
        ).map { it.id }
        assertEquals(
            listOf(
                "landslide", "keystone-flip", "swing-sweep", "debate-dominator",
                "grassroots", "war-chest", "comeback", "beltway", "sun-belt",
                "blue-wall", "steady-hand", "dirt-digger", "vp-mvp",
                "coast-to-coast", "history-defied", "money-machine",
            ),
            ids,
        )
    }

    @Test
    fun achievementsEmptyWithoutResult() {
        val g = achGame()
        val ids = checkAchievements(
            AchievementContext(
                result = g.result!!,
                game = g.copy(result = null), player = CandidateId.DEM, difficulty = "easy",
            ),
        ).map { it.id }
        assertTrue(ids.isEmpty())
    }
}
