package com.lakesidegames.electioneer.engine

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

// Phase 1, issue #13: Rng must reproduce the TS stream exactly for fixed
// seeds. Every expected value below was generated by running the real
// src/engine/rng.ts (scripts in /tmp, never committed); they are
// cross-checked values, not statistical shape.
class RngTest {

    @Test
    fun hashSeedMatchesTs() {
        assertEquals(2949673445L, Rng.hashSeed("test"))
        assertEquals(1261010898L, Rng.hashSeed("ct"))
        assertEquals(81344972L, Rng.hashSeed("noise-0"))
        assertEquals(839689206L, Rng.hashSeed("7"))
        assertEquals(2166136261L, Rng.hashSeed(""))
    }

    @Test
    fun nextStreamMatchesTsForNumericSeed() {
        val r = Rng.createRng(7)
        val expected = listOf(
            0.011704753153026104, 0.06195825757458806, 0.97690763277933,
            0.6990287057124078, 0.5214452685322613, 0.4055216880515218,
            0.4662326325196773, 0.23992518591694534,
        )
        for (e in expected) assertEquals(e, r.next())
        assertEquals(1030470827L, r.state())
    }

    @Test
    fun nextStreamMatchesTsForStringSeed() {
        val r = Rng.createRng("ct")
        val expected = listOf(
            0.7087304403539747, 0.06696969061158597, 0.11693262308835983,
            0.34351081354543567, 0.46389824291691184, 0.3815428502857685,
            0.6759385650511831, 0.7292961562052369,
        )
        for (e in expected) assertEquals(e, r.next())
    }

    @Test
    fun intMatchesTs() {
        val r = Rng.createRng(7)
        assertEquals(listOf(1, 1, 6, 5, 4, 3), List(6) { r.int(1, 6) })
    }

    @Test
    fun normalMatchesTs() {
        val r = Rng.createRng(7)
        val expected = listOf(
            2.759372987028844, -0.06805135650735404, -0.9459489604452885,
            0.07814913415014278, -0.1375617329034767,
        )
        for (e in expected) assertEquals(e, r.normal())
    }

    @Test
    fun normalWithMeanAndStdevMatchesTs() {
        val r = Rng.createRng(7)
        val expected = listOf(
            141.39059480543267, 98.97922965238969, 85.81076559332067,
            101.17223701225214, 97.93657400644786,
        )
        for (e in expected) assertEquals(e, r.normal(100.0, 15.0))
    }

    @Test
    fun pickMatchesTs() {
        val r = Rng.createRng(99)
        val items = listOf("a", "b", "c", "d")
        assertEquals(listOf("b", "d", "c", "c", "a", "d"), List(6) { r.pick(items) })
    }

    @Test
    fun weightedPickMatchesTs() {
        val r = Rng.createRng(99)
        val items = listOf("a", "b", "c")
        assertEquals(
            listOf("b", "c", "c", "c", "a", "c"),
            List(6) { r.weightedPick(items, listOf(1.0, 2.0, 7.0)) },
        )
    }

    @Test
    fun chanceMatchesTs() {
        val r = Rng.createRng(99)
        assertEquals(
            listOf(true, false, false, false, true, false, true, true),
            List(8) { r.chance(0.3) },
        )
    }

    @Test
    fun forkMatchesTs() {
        val r = Rng.createRng(42)
        repeat(3) { r.next() }
        assertEquals(3661312704L, r.state())
        val child = r.fork(1)
        assertEquals(
            listOf(0.8823747518472373, 0.9783809066284448, 0.3788255506660789),
            List(3) { child.next() },
        )
        // Parent stream is unaffected by the fork.
        assertEquals(
            listOf(0.6697340414393693, 0.17481389874592423),
            List(2) { r.next() },
        )
    }

    @Test
    fun stringSeedWithColonsMatchesTs() {
        assertEquals(0.5357390623539686, Rng.createRng("421:7:123456").next())
    }

    @Test
    fun nextStaysInUnitInterval() {
        val r = Rng.createRng("soak")
        repeat(10000) {
            val v = r.next()
            assertTrue(v >= 0.0 && v < 1.0)
        }
    }
}
